SCREEN_WIDTH = 1920
SCREEN_HEIGHT = 1080

ASTEROID_MIN_RADIUS = 20
ASTEROID_KINDS = 3
ASTEROID_SPAWN_RATE = 1.5  # seconds
ASTEROID_MAX_RADIUS = ASTEROID_MIN_RADIUS * ASTEROID_KINDS
ASTEROID_TIME_TO_LIVE = 120 # seconds

PLAYER_RADIUS = 20
PLAYER_TURN_SPEED = 300
PLAYER_SPEED = 10
PLAYER_REVERSE_SPEED_MODIFIER = 0.25
PLAYER_RETROGRADE_SPEED = PLAYER_SPEED * PLAYER_REVERSE_SPEED_MODIFIER
SHOT_TIME_TO_LIVE = 7 #secondsW
SHOT_RADIUS = 2
PLAYER_SHOT_SPEED = 400
PLAYER_SHOOT_COOLDOWN = 0.3